twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        articles: '@App\TwigExtension\ArticlesExtension'
        categories: '@App\TwigExtension\CategoriesExtension'
        websitetwig: '@App\TwigExtension\WebsitesExtension'

when@test:
    twig:
        strict_variables: true
